// app/api/operations/route.ts
import { NextResponse } from "next/server";

export async function POST() {
  try {
    // Sample JSON object mimicking the operation list API response
    const sampleOperationData = [
        {
            "TrnNo": 0,
            "TrnDate": null,
            "TrnSubType": 0,
            "DocType": null,
            "StatusCode": 0,
            "CrtBy": null,
            "AssetCode": 0,
            "MaterialCode": 0,
            "OperationCode": 1010000001,
            "MaterialName": null,
            "JobNo": 0,
            "JobNoString": null,
            "ShortTrnNo": null,
            "OperationName": "1st OPERATION",
            "FirstPieceApprovals": null,
            "ProcessInpections": null,
            "AssetName": null,
            "ChgBy": null,
            "ShiftCode": 0,
            "ShiftName": null,
            "JobStatus": 0,
            "PirType": 0,
            "ReasonCode": 0,
            "ReasonName": null,
            "StringTrnNo": null,
            "GuageCode": 0,
            "GuageName": null,
            "FromSpecification": null,
            "ToSpecification": null,
            "ActualSpecification": null,
            "JobDate": null
        },
        {
            "TrnNo": 0,
            "TrnDate": null,
            "TrnSubType": 0,
            "DocType": null,
            "StatusCode": 0,
            "CrtBy": null,
            "AssetCode": 0,
            "MaterialCode": 0,
            "OperationCode": 1010000002,
            "MaterialName": null,
            "JobNo": 0,
            "JobNoString": null,
            "ShortTrnNo": null,
            "OperationName": "2nd OPERATION",
            "FirstPieceApprovals": null,
            "ProcessInpections": null,
            "AssetName": null,
            "ChgBy": null,
            "ShiftCode": 0,
            "ShiftName": null,
            "JobStatus": 0,
            "PirType": 0,
            "ReasonCode": 0,
            "ReasonName": null,
            "StringTrnNo": null,
            "GuageCode": 0,
            "GuageName": null,
            "FromSpecification": null,
            "ToSpecification": null,
            "ActualSpecification": null,
            "JobDate": null
        },
        {
            "TrnNo": 0,
            "TrnDate": null,
            "TrnSubType": 0,
            "DocType": null,
            "StatusCode": 0,
            "CrtBy": null,
            "AssetCode": 0,
            "MaterialCode": 0,
            "OperationCode": 1010000003,
            "MaterialName": null,
            "JobNo": 0,
            "JobNoString": null,
            "ShortTrnNo": null,
            "OperationName": "3rd OPERATION",
            "FirstPieceApprovals": null,
            "ProcessInpections": null,
            "AssetName": null,
            "ChgBy": null,
            "ShiftCode": 0,
            "ShiftName": null,
            "JobStatus": 0,
            "PirType": 0,
            "ReasonCode": 0,
            "ReasonName": null,
            "StringTrnNo": null,
            "GuageCode": 0,
            "GuageName": null,
            "FromSpecification": null,
            "ToSpecification": null,
            "ActualSpecification": null,
            "JobDate": null
        },
        {
            "TrnNo": 0,
            "TrnDate": null,
            "TrnSubType": 0,
            "DocType": null,
            "StatusCode": 0,
            "CrtBy": null,
            "AssetCode": 0,
            "MaterialCode": 0,
            "OperationCode": 1010000004,
            "MaterialName": null,
            "JobNo": 0,
            "JobNoString": null,
            "ShortTrnNo": null,
            "OperationName": "4th OPERATION",
            "FirstPieceApprovals": null,
            "ProcessInpections": null,
            "AssetName": null,
            "ChgBy": null,
            "ShiftCode": 0,
            "ShiftName": null,
            "JobStatus": 0,
            "PirType": 0,
            "ReasonCode": 0,
            "ReasonName": null,
            "StringTrnNo": null,
            "GuageCode": 0,
            "GuageName": null,
            "FromSpecification": null,
            "ToSpecification": null,
            "ActualSpecification": null,
            "JobDate": null
        },
        {
            "TrnNo": 0,
            "TrnDate": null,
            "TrnSubType": 0,
            "DocType": null,
            "StatusCode": 0,
            "CrtBy": null,
            "AssetCode": 0,
            "MaterialCode": 0,
            "OperationCode": 1010000005,
            "MaterialName": null,
            "JobNo": 0,
            "JobNoString": null,
            "ShortTrnNo": null,
            "OperationName": "FINAL OPERATION",
            "FirstPieceApprovals": null,
            "ProcessInpections": null,
            "AssetName": null,
            "ChgBy": null,
            "ShiftCode": 0,
            "ShiftName": null,
            "JobStatus": 0,
            "PirType": 0,
            "ReasonCode": 0,
            "ReasonName": null,
            "StringTrnNo": null,
            "GuageCode": 0,
            "GuageName": null,
            "FromSpecification": null,
            "ToSpecification": null,
            "ActualSpecification": null,
            "JobDate": null
        }
    ]
    

    return NextResponse.json(sampleOperationData, { status: 200 });
  } catch (error) {
    console.error("Error returning sample operation list:", error);
    return NextResponse.json(
      { error: "Failed to return sample operation list" },
      { status: 500 }
    );
  }
}