import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'

const font = Lexend({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "SPC Data Visualizer",

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${font.className} antialiased`}>{children}</body>
    </html>
  );
}
